### ISSUE TITLE
Compilation error: setState should not return a value

### ISSUE THREAD

**Issue by asarasua** [bcaramiaux/ofxGVF#13]
I get a "void function 'setState' should not return a value" compilation error in GVF.cpp due to the `return` statements in `GVF::setState`.

**Comment by bcaramiaux** [comment]
`GVF::setState` doesn't return the state anymore but void. Since the state is given as an argument, it assumes that the interface knows already in which state GVF

**Comment by asarasua** [comment]
These are issues I got when trying to compile the current version in master branch.

Indeed, `GVF::setState` is declared as a void function, but it has `return` statements of `GVFState` type variables such as:

```cpp
case STATE_CLEAR:
  clear();
  theGesture.clear();
  return STATE_CLEAR;
```

At least I get a compiler error because of this that I [solved](https://github.com/asarasua/ofxGVF/commit/ab07d0ef5877018acedbd671b2be0125a2c53f84) substituting those by `break` statements.

**Comment by bcaramiaux** [comment]
Ok fixed.
