### ISSUE TITLE
Compilation error in OF: random number generator variables, private members of GVF

### ISSUE THREAD

**Issue by asarasua** [bcaramiaux/ofxGVF#14]
I get a "private member of 'GVF'" compilation error in ofxGVF.h at:

```cpp
// Init random generators
normgen = std::mt19937(rd());
rndnorm = new std::normal_distribution<float>(0.0,1.0);
unifgen = std::default_random_engine(rd());
rndunif = new std::uniform_real_distribution<float>(0.0,1.0);
```

All those variables are private members of GVH.h

**Comment by bcaramiaux** [comment]
they are indeed private, why would you need to access the GVF's specific random number generators? In case you need in your interface, I suggest you to declare your own

**Comment by asarasua** [comment]
This is an issue I got trying to compile the [openFrameworks 2d-shapes example](https://github.com/bcaramiaux/ofxGVF/tree/master/openFrameworks/example-2dShapes) in the current master branch version. 

The [ofxGVF.h](https://github.com/bcaramiaux/ofxGVF/blob/master/openFrameworks/ofxGVF/src/ofxGVF.h) openFrameworks interface for the `GVF` class contains the following:

```cpp
// Init random generators
normgen = std::mt19937(rd());
rndnorm = new std::normal_distribution<float>(0.0,1.0);
unifgen = std::default_random_engine(rd());
rndunif = new std::uniform_real_distribution<float>(0.0,1.0);
```

Using variables derived from `GVF` which are declared as `private`. I couldn't compile it until I [switched](https://github.com/asarasua/ofxGVF/commit/beeb21fbe935311d3c30166c08a6e8264d53ade8) those to `protected` (so that a derived class such as `ofxGVF` can use them)

**Comment by bcaramiaux** [comment]
I dont't have this error copying [openFrameworks 2d-shapes example](https://github.com/bcaramiaux/ofxGVF/tree/master/openFrameworks/example-2dShapes) into oF apps/myApps folder and by also copying  [openFrameworks ofxGVF](https://github.com/bcaramiaux/ofxGVF/blob/master/openFrameworks/ofxGVF) into the oF addons folder. 

It shouldn't matter, but which version of openFrameworks are you using? I tested with 0.9

**Comment by bcaramiaux** [comment]
OK the issue was in ofxGVF.h when calling GVF lib. I fixed the issue in the master branch, thanks for spotting it
