### ISSUE TITLE
more than 2 dimensions in Max?

### ISSUE THREAD

**Issue by jamesstaub** [bcaramiaux/ofxGVF#18]
Hello

When I record gestures with more than 2 dimensions in Max MSP, the patch always crashes when I send the `follow` message. 

Does the max version support greater than 2D gestures?

**Comment by bcaramiaux** [comment]
GVF can be used with any number of dimensions. GVF is now a MuBu Max object, more here https://forum.ircam.fr/projects/detail/mubu/
